// test_gear_math_involute.cpp — external involute gear tooth math, checked
// against a real oracle: values computed by RUNNING the actual upstream
// `pygears.involute_tooth.InvoluteTooth` (freecad.gears v1.3.0, GPL-3.0,
// commit pinned to the `master` branch as fetched during the Gear Generator
// implementation plan's G0 phase), not re-derived by hand. This is the
// project's cross-check-harness posture (Gear Generator plan §10.1 leg 2)
// applied at unit-test scale: a formula transcription bug shows up here as a
// tolerance failure, not as "my C++ agrees with my own re-derivation."
//
// No test framework (matches the prototype style, see test_polygon_fill.cpp):
// exit code == failure count.
#include <cmath>
#include <cstdio>
#include <vector>

#include "kernel/gear/InvoluteMath.h"

namespace gear = onecad::kernel::gear;

namespace {
int g_failures = 0;
#define CHECK(cond)                                                              \
    do {                                                                         \
        if (!(cond)) {                                                           \
            std::fprintf(stderr, "FAIL %s:%d: %s\n", __FILE__, __LINE__, #cond); \
            ++g_failures;                                                        \
        }                                                                        \
    } while (0)

constexpr double kPi = 3.14159265358979323846;
constexpr double kTol = 1e-7;

void CHECK_NEAR(double actual, double expected, const char* what, const char* caseName) {
    if (std::abs(actual - expected) > kTol) {
        std::fprintf(stderr, "FAIL %s: %s mismatch: actual=%.12f expected=%.12f (case %s)\n",
                     __FILE__, what, actual, expected, caseName);
        ++g_failures;
    }
}

void CHECK_POINT_NEAR(const gear::Point2d& actual, const gear::Point2d& expected,
                       const char* what, const char* caseName) {
    if (std::abs(actual.x - expected.x) > kTol || std::abs(actual.y - expected.y) > kTol) {
        std::fprintf(stderr,
                     "FAIL %s: %s mismatch: actual=(%.12f,%.12f) expected=(%.12f,%.12f) (case %s)\n",
                     __FILE__, what, actual.x, actual.y, expected.x, expected.y, caseName);
        ++g_failures;
    }
}

double deg(double d) { return d * kPi / 180.0; }

// --- Oracle: pygears.involute_tooth.InvoluteTooth, `num=7` sampling for the
//     factors + involute/undercut point checks. Generated by running the
//     actual upstream module locally (never wired into this repo or CI —
//     GPL-3.0 code stays out per the Gear Generator plan §11/§10.1). ---

struct OracleCase {
    const char* name;
    gear::InvoluteToothParams params;
    // factors
    double pressureAngleTransverse, transverseModule, transversePitch, clearanceAbs,
        referenceDiameter, workingDiameter, addendumDiameter, rootDiameter, baseDiameter,
        angularPitch, undercutEnd, undercutRot, involuteEnd, involuteRot1, involuteRot2,
        involuteRot, angularBacklash, involuteStart;
    // involute_points(num=7)[0] and [6] (endpoints suffice to pin sampling + rotation)
    gear::Point2d involFirst, involLast;
    gear::Point2d undercutFirst, undercutLast;
};

const OracleCase kCases[] = {
    {
        "m2_z20_a20_shift0",
        {2.0, 20, deg(20.0), 0.25, 0.0, 0.0, false, 0.0, 0.0, false},
        0.3490658503988659, 2.0, 6.283185307179586, 0.5, 40.0, 40.0, 44.0, 35.0,
        37.58770483143634, 0.3141592653589793, 0.6060132557260629, -0.033043537056469535,
        0.6085178231017319, 0.01490438386733639, 0.07853981633974483, 0.09344420020708122,
        0.0, 0.0,
        {18.711859849196124, -1.7536218542883621}, {21.989026862476454, -0.694764450219579},
        {17.36555416401329, -2.165070108961987}, {21.126939600782006, -2.6418074596302743},
    },
    {
        "m1_z15_a20_shift0_undercut",
        {1.0, 15, deg(20.0), 0.25, 0.0, 0.0, true, 0.0, 0.0, false},
        0.3490658503988659, 1.0, 3.141592653589793, 0.25, 15.0, 15.0, 17.0, 12.5,
        14.095389311788626, 0.41887902047863906, 0.6777481542237007, -0.04405804940862605,
        0.6742405827918582, 0.014904383867336446, 0.10471975511965977, 0.11962413898699621,
        0.0, 0.0,
        {6.997328735075125, -0.8410651199599332}, {8.493664740179511, -0.32811473821109466},
        {6.164722673432569, -1.0289287437264043}, {7.922775062234308, -1.2657304317466518},
    },
    {
        "m3_z12_a20_shift0.5",
        {3.0, 12, deg(20.0), 0.25, 0.5, 0.0, false, 0.0, 0.0, false},
        0.3490658503988659, 3.0, 9.42477796076938, 0.75, 36.0, 36.0, 45.0, 31.5,
        33.828934348292705, 0.5235987755982988, 0.7141428428542851, -0.055072561760782554,
        0.8772064425562424, 0.01490438386733639, 0.16123054675509157, 0.17613493062242797,
        0.0, 0.0,
        {16.65277168160442, -2.9638480233690108}, {22.495935969681014, -0.4276269963551464},
        {15.41465099807107, -3.232805995983456}, {20.189740930599555, -5.176738951395671},
    },
    {
        "m2_z30_a14.5_shift0_backlash0.1",
        {2.0, 30, deg(14.5), 0.25, 0.0, 0.0, false, 0.1, 0.0, false},
        0.2530727415391778, 2.0, 6.283185307179586, 0.5, 60.0, 60.0, 64.0, 55.0,
        58.088858422686464, 0.20943951023931953, 0.5113458803735491, -0.03080841219683902,
        0.4624671138537432, 0.005544842816712525, 0.05235987755982988, 0.05790472037654241,
        0.0033333333333333335, 0.0,
        {28.99851163580639, -1.632541307510907}, {31.988385022073974, -0.8621042161790244},
        {27.428265926089953, -1.9850008281340268}, {31.444287966750068, -2.3711409735710403},
    },
    {
        // propertiesFromTool=true: exercises the transverse-recompute branch
        // (pressureAngleTransverse via atan(tan/cos(helix)), transverseModule
        // via module/cos(helix)) that every other case above bypasses.
        "m2_z20_a20_shift0.2_helix25_fromTool",
        {2.0, 20, deg(20.0), 0.25, 0.2, deg(25.0), false, 0.0, 0.0, true},
        0.3818821012359087, 2.2067558379249834, 6.932727928691516, 0.5, 44.13511675849967,
        44.13511675849967, 48.93511675849967, 39.93511675849967, 40.955838384338946,
        0.3141592653589793, 0.5779347207813077, -0.033043537056469535, 0.6539190437626198,
        0.019714618413024243, 0.0865717507327235, 0.10628636914574774, 0.0, 0.0,
        {20.362360640811023, -2.172428036684511}, {24.45542607591817, -0.770420980568827},
        {19.814155231883454, -2.470352216906701}, {23.618271315979385, -3.2381762921868775},
    },
    {
        // head=0.3 — the ONLY case exercising the extra-addendum term. Added
        // after a mutation probe (deleting `head` from the `da` formula)
        // survived the whole suite: every other case here sets head = 0, so
        // the parameter was inert in the oracle. `da` = 41.2 here versus 40.0
        // without the term, so this case now pins it.
        "m2_z18_a20_head0.3",
        {2.0, 18, deg(20.0), 0.25, 0.0, 0.0, false, 0.0, 0.3, false},
        0.3490658503988659, 2, 6.2831853071795862, 0.5, 36, 36, 41.200000000000003, 31,
        33.828934348292705,
        0.3490658503988659, 0.65867543758404934, -0.036715041173855038, 0.69517030351126108,
        0.01490438386733639, 0.087266462599716474, 0.10217084646705286, 0, 0,
        {16.826259883992513, -1.7251603118605405}, {20.597841106576993, -0.29823103159675146},
        {15.353031134510379, -2.1294212788349189}, {19.392840668387702, -2.844300833401777},
    },
};

// --- Oracle: full `points(num=5)` tooth-segment assemblies, for the three
//     structurally distinct branches this port's test cases exercise:
//       - !undercut, dg > df   (5 segments, root-blend synthetic point)
//       - undercut, nearestpts fallback (5 segments, variable u1 length)
//       - !undercut, dg <= df  (3 segments, no root blend)
//     The `trimfunc`-crossing-found branch is implemented (see
//     InvoluteMath.cpp) but not exercised by any case here — no parameter
//     combination tried during oracle generation made the sampled undercut
//     and involute polylines actually cross. Flagged, not silently assumed
//     correct: a future case that DOES cross should be added here before
//     that branch is trusted for a real undercut gear.
struct ToothOracleCase {
    const char* name;
    gear::InvoluteToothParams params;
    int sampleCount;
    std::vector<std::vector<gear::Point2d>> segments;
};

const ToothOracleCase kToothCases[] = {
    {
        "m2_z20_a20_shift0 (dg>df, no undercut)",
        {2.0, 20, deg(20.0), 0.25, 0.0, 0.0, false, 0.0, 0.0, false},
        5,
        {
            {{17.42365216654911, -1.632894723828959}, {18.711859849196124, -1.7536218542883621}},
            {{18.711859849196124, -1.7536218542883621},
             {18.92918970849014, -1.7518875719633065},
             {19.574341449755423, -1.6588620425561673},
             {20.61471975630041, -1.3461865183205661},
             {21.989026862476454, -0.694764450219579}},
            {{21.989026862476454, -0.694764450219579}, {21.989026862476454, 0.694764450219579}},
            {{21.989026862476454, 0.694764450219579},
             {20.61471975630041, 1.3461865183205661},
             {19.574341449755423, 1.6588620425561673},
             {18.92918970849014, 1.7518875719633065},
             {18.711859849196124, 1.7536218542883621}},
            {{18.711859849196124, 1.7536218542883621}, {17.42365216654911, 1.632894723828959}},
        },
    },
    {
        "m1_z15_a20_shift0_undercut (nearestpts fallback)",
        {1.0, 15, deg(20.0), 0.25, 0.0, 0.0, true, 0.0, 0.0, false},
        5,
        {
            {{6.164722673432569, -1.0289287437264043},
             {6.280075176912121, -0.8754516706225871},
             {7.097368507342569, -0.8417899001728942}},
            {{7.097368507342569, -0.8417899001728942},
             {7.394345770928121, -0.7991561749735574},
             {7.87092927485483, -0.6478598103940192},
             {8.493664740179511, -0.32811473821109466}},
            {{8.493664740179511, -0.32811473821109466}, {8.493664740179511, 0.32811473821109466}},
            {{8.493664740179511, 0.32811473821109466},
             {7.87092927485483, 0.6478598103940192},
             {7.394345770928121, 0.7991561749735574},
             {7.097368507342569, 0.8417899001728942}},
            {{7.097368507342569, 0.8417899001728942},
             {6.280075176912121, 0.8754516706225871},
             {6.164722673432569, 1.0289287437264043}},
        },
    },
    {
        "m3_z12_a20_shift1.0 (dg<=df, no undercut, no blend)",
        {3.0, 12, deg(20.0), 0.25, 1.0, 0.0, false, 0.0, 0.0, false},
        5,
        {
            {{16.892812163615623, -3.492190888940629},
             {17.9117939178132, -3.3840080730610302},
             {19.5449718318351, -2.873671649610536},
             {21.645967545908782, -1.7189272800837119},
             {23.998424600714962, 0.27498487921868314}},
            {{23.998424600714962, 0.27498487921868314}, {23.998424600714962, -0.27498487921868314}},
            {{23.998424600714962, -0.27498487921868314},
             {21.645967545908782, 1.7189272800837119},
             {19.5449718318351, 2.873671649610536},
             {17.9117939178132, 3.3840080730610302},
             {16.892812163615623, 3.492190888940629}},
        },
    },
};

}  // namespace

int main() {
    for (const auto& c : kCases) {
        const gear::InvoluteFactorsResult r = gear::compute_involute_factors(c.params);
        CHECK(r.ok);
        if (!r.ok) {
            std::fprintf(stderr, "  (case %s error: %s)\n", c.name, r.error.c_str());
            continue;
        }
        const gear::InvoluteToothFactors& f = r.factors;
        CHECK_NEAR(f.pressureAngleTransverse, c.pressureAngleTransverse, "pressureAngleTransverse", c.name);
        CHECK_NEAR(f.transverseModule, c.transverseModule, "transverseModule", c.name);
        CHECK_NEAR(f.transversePitch, c.transversePitch, "transversePitch", c.name);
        CHECK_NEAR(f.clearanceAbs, c.clearanceAbs, "clearanceAbs", c.name);
        CHECK_NEAR(f.referenceDiameter, c.referenceDiameter, "referenceDiameter", c.name);
        CHECK_NEAR(f.workingDiameter, c.workingDiameter, "workingDiameter", c.name);
        CHECK_NEAR(f.addendumDiameter, c.addendumDiameter, "addendumDiameter", c.name);
        CHECK_NEAR(f.rootDiameter, c.rootDiameter, "rootDiameter", c.name);
        CHECK_NEAR(f.baseDiameter, c.baseDiameter, "baseDiameter", c.name);
        CHECK_NEAR(f.angularPitch, c.angularPitch, "angularPitch", c.name);
        CHECK_NEAR(f.undercutEnd, c.undercutEnd, "undercutEnd", c.name);
        CHECK_NEAR(f.undercutRot, c.undercutRot, "undercutRot", c.name);
        CHECK_NEAR(f.involuteEnd, c.involuteEnd, "involuteEnd", c.name);
        CHECK_NEAR(f.involuteRot1, c.involuteRot1, "involuteRot1", c.name);
        CHECK_NEAR(f.involuteRot2, c.involuteRot2, "involuteRot2", c.name);
        CHECK_NEAR(f.involuteRot, c.involuteRot, "involuteRot", c.name);
        CHECK_NEAR(f.angularBacklash, c.angularBacklash, "angularBacklash", c.name);
        CHECK_NEAR(f.involuteStart, c.involuteStart, "involuteStart", c.name);

        const auto invPts = gear::involute_points(f, 7);
        CHECK(invPts.size() == 7);
        CHECK_POINT_NEAR(invPts.front(), c.involFirst, "involute_points[0]", c.name);
        CHECK_POINT_NEAR(invPts.back(), c.involLast, "involute_points[6]", c.name);

        const auto uncPts = gear::undercut_points(f, 7);
        CHECK(uncPts.size() == 7);
        CHECK_POINT_NEAR(uncPts.front(), c.undercutFirst, "undercut_points[0]", c.name);
        CHECK_POINT_NEAR(uncPts.back(), c.undercutLast, "undercut_points[6]", c.name);
    }

    for (const auto& c : kToothCases) {
        const gear::InvoluteFactorsResult r = gear::compute_involute_factors(c.params);
        CHECK(r.ok);
        if (!r.ok) {
            std::fprintf(stderr, "  (tooth case %s error: %s)\n", c.name, r.error.c_str());
            continue;
        }
        const gear::ToothProfile profile =
            gear::one_tooth_profile(c.params, r.factors, c.sampleCount);
        CHECK(profile.segments.size() == c.segments.size());
        if (profile.segments.size() != c.segments.size()) {
            std::fprintf(stderr, "  (tooth case %s: got %zu segments, expected %zu)\n", c.name,
                         profile.segments.size(), c.segments.size());
            continue;
        }
        for (std::size_t s = 0; s < c.segments.size(); ++s) {
            CHECK(profile.segments[s].size() == c.segments[s].size());
            if (profile.segments[s].size() != c.segments[s].size()) {
                std::fprintf(stderr, "  (tooth case %s segment %zu: got %zu points, expected %zu)\n",
                             c.name, s, profile.segments[s].size(), c.segments[s].size());
                continue;
            }
            for (std::size_t i = 0; i < c.segments[s].size(); ++i) {
                char what[64];
                std::snprintf(what, sizeof(what), "segment[%zu][%zu]", s, i);
                CHECK_POINT_NEAR(profile.segments[s][i], c.segments[s][i], what, c.name);
            }
        }
        // Continuity invariant every branch must hold regardless of oracle
        // coverage: each segment's last point equals the next segment's
        // first point (this is what lets a wire builder concatenate them).
        for (std::size_t s = 0; s + 1 < profile.segments.size(); ++s) {
            const auto& a = profile.segments[s].back();
            const auto& b = profile.segments[s + 1].front();
            CHECK(std::abs(a.x - b.x) < 1e-9 && std::abs(a.y - b.y) < 1e-9);
        }
    }

    // --- Domain refusal matrix: bad params must fail closed with a message,
    //     never silently produce NaN factors (see InvoluteMath.h). ---
    {
        gear::InvoluteToothParams p;
        p.numTeeth = 2;
        const auto r = gear::compute_involute_factors(p);
        CHECK(!r.ok);
        CHECK(!r.error.empty());
    }
    {
        gear::InvoluteToothParams p;
        p.module = 0.0;
        const auto r = gear::compute_involute_factors(p);
        CHECK(!r.ok);
    }
    {
        gear::InvoluteToothParams p;
        p.pressureAngle = 0.0;
        const auto r = gear::compute_involute_factors(p);
        CHECK(!r.ok);
    }
    {
        gear::InvoluteToothParams p;
        p.pressureAngle = kPi / 2.0;
        const auto r = gear::compute_involute_factors(p);
        CHECK(!r.ok);
    }
    {
        // Extreme negative shift can push the root diameter non-positive.
        gear::InvoluteToothParams p;
        p.numTeeth = 5;
        p.shift = -5.0;
        const auto r = gear::compute_involute_factors(p);
        CHECK(!r.ok);
    }
    // A sane default set must still succeed (negative control for the
    // refusal matrix above).
    {
        gear::InvoluteToothParams p;  // defaults: m=5, z=15, 20deg, shift=0, clearance=0.25
        const auto r = gear::compute_involute_factors(p);
        CHECK(r.ok);
    }

    if (g_failures == 0) {
        std::fprintf(stderr, "OK: gear_math_involute\n");
    }
    // Exit status is 8-bit on POSIX, so returning a raw failure count reports
    // SUCCESS whenever that count is a multiple of 256 — this file's sweeps
    // can produce thousands. Clamp to a nonzero cap so a failing run can never
    // masquerade as a passing one, while small counts stay readable.
    return (g_failures == 0) ? 0 : (g_failures > 100 ? 100 : g_failures);
}
