//! VF-B1 gate — a colored body's MESH1 blob must survive Rust validation.
//!
//! The worker sets `flags` bit `0x0010` (`HAS_FACE_COLORS`) whenever it emits the
//! FACE_COLORS section (`worker/src/tess/Mesh1.cpp`), and `mesh_format.md` §2 has
//! carried that bit since WP-A W4.5. `FLAGS_KNOWN_MASK` did not, so
//! `validate_mesh_blob` rejected the blob, `fetch_mesh` returned `Err`, `get_mesh`
//! returned `None`, and every colored body silently failed to render. No existing
//! suite covered the seam: the color gate is C++-side (ctest), and the FE/e2e lanes
//! run the mock client.
//!
//! Fixture provenance: `src-tauri/tests/fixtures/colored_boxes.step` was generated by
//! `stepfx::write_colored_step_fixture` (`worker/tests/step_fixture_util.h`, the same
//! helper the ctest color gate calls) at commit `596d30e`, via a throwaway `main`
//! linked against `worker/build/libworker_core.a`. It is two named XCAF solids:
//! `PartA` (20×30×40) with four per-face colors, `PartB` (10×10×10) with one
//! whole-solid color that XCAF resolves onto all six of its faces.
//!
//! REQUIRE_WORKER-guarded (CI hard-fails without a worker; local dev skips cleanly).

use std::path::{Path, PathBuf};
use std::sync::Arc;
use std::time::Duration;

use onecad_core::ids::SnapshotId;
use onecad_core::regen::{CancelToken, GeometryEngine, Lod, Outcome, RegenRequest};

use onecad_lib::document_runtime::DocumentRuntime;
use onecad_lib::imports::prepare_import;
use onecad_lib::worker::manager::SupervisorConfig;
use onecad_lib::worker::{resolve_worker_path, MeshProvider, SolverEngine, WorkerManager};

use onecad_protocol::mesh::{validate_mesh_blob, FLAG_HAS_FACE_COLORS};

/// FACE_COLORS section type (`protocol/mesh_format.md` §4).
const SEC_FACE_COLORS: u32 = 12;

// ─────────────────────────────────────────────────────────────────────────────
// Harness (mirrors step_import.rs)
// ─────────────────────────────────────────────────────────────────────────────

fn real_worker() -> Option<PathBuf> {
    if let Ok(p) = std::env::var("ONECAD_WORKER_PATH") {
        let path = PathBuf::from(&p);
        assert!(
            path.is_file(),
            "ONECAD_WORKER_PATH={p:?} is set but no worker binary exists there \
             (misconfiguration — refusing to skip as green)"
        );
        return Some(path);
    }
    if let Some(path) = resolve_worker_path() {
        return Some(path);
    }
    assert!(
        std::env::var("ONECAD_REQUIRE_WORKER").as_deref() != Ok("1"),
        "ONECAD_REQUIRE_WORKER=1 but no worker binary resolved (CI must hard-fail here)"
    );
    None
}

async fn spawn_worker(bin: PathBuf) -> WorkerManager {
    let wm = WorkerManager::spawn(SupervisorConfig::production(bin));
    assert!(
        wm.wait_ready(Duration::from_secs(10)).await,
        "real worker must connect + handshake + OpenSession"
    );
    wm
}

fn runtime_over(wm: &WorkerManager) -> DocumentRuntime {
    let engine: Arc<dyn GeometryEngine> = Arc::new(wm.clone());
    let meshes: Arc<dyn MeshProvider> = Arc::new(wm.clone());
    let solver: Arc<dyn SolverEngine> = Arc::new(wm.clone());
    DocumentRuntime::new_blank(engine, meshes, solver)
}

fn fixture() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/colored_boxes.step")
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn colored_import_meshes_pass_validation_and_carry_face_colors() {
    let Some(bin) = real_worker() else {
        eprintln!("skip: no worker binary (set ONECAD_WORKER_PATH)");
        return;
    };
    let step = fixture();
    assert!(step.is_file(), "checked-in fixture missing at {step:?}");

    let wm = spawn_worker(bin).await;
    let mut rt = runtime_over(&wm);

    // The runtime-side half of the `import_step` command (probe + author), exactly as
    // `step_import.rs::do_import` drives it.
    let prepared = prepare_import(&wm, &step).await.expect("prepare_import");
    assert_eq!(prepared.solid_count, 2, "the fixture carries two solids");
    rt.add_import_record(&prepared, false)
        .expect("author the ImportStep record");

    let report = rt
        .run_regen(RegenRequest::ToEnd { from: 0 }, CancelToken::new())
        .await;
    match &report.outcome {
        Outcome::Published(s) => assert_eq!(s.bodies.len(), 2, "two solids ⇒ two bodies"),
        other => panic!("import regen: expected Published, got {other:?}"),
    }
    let snapshot = SnapshotId(report.snapshot_id);

    // Pull each body's mesh THROUGH the provider — `WorkerManager::fetch_mesh` runs
    // `verify_mesh` → `validate_mesh_blob`, which is the seam that rejected the blob.
    let bodies = rt.head_body_ids();
    let mut colored = 0usize;
    for body in bodies {
        let mesh = wm
            .fetch_mesh(body, Lod::Coarse, snapshot)
            .await
            .unwrap_or_else(|e| {
                panic!(
                    "body {body}: a colored MESH1 blob must pass provider validation \
                     (VF-B1 — FLAGS_KNOWN_MASK omitted HAS_FACE_COLORS): {e}"
                )
            });
        // The production pull path (cache + snapshot generation) must serve it too —
        // this is what returns `None` to the frontend when validation rejects a blob.
        assert!(
            rt.get_mesh(body, Lod::Coarse, None).await.is_some(),
            "body {body} has no mesh on the pull path — it would never render"
        );
        let view = validate_mesh_blob(&mesh).expect("colored MESH1 blob is valid");
        if view.flags & FLAG_HAS_FACE_COLORS == 0 {
            continue;
        }
        colored += 1;
        let section = view
            .section(SEC_FACE_COLORS)
            .expect("HAS_FACE_COLORS is set ⇒ the FACE_COLORS section is present");
        assert_eq!(
            section.byte_len as usize,
            view.face_count as usize * 4,
            "FACE_COLORS is u8×4 per face (mesh_format.md §4)"
        );
    }
    assert_eq!(
        colored, 2,
        "both imported bodies carry authored XCAF colors, so both meshes must declare \
         HAS_FACE_COLORS"
    );

    wm.shutdown().await;
}
